### ISSUE TITLE
Document icon interference

### ISSUE THREAD

**Issue by okonomiyaki3000** [equinusocio/preap#10]
So, the situation is that I have preap installed but my active theme is actually a different one (aprosopo) and somehow preap is causing the document icons for some (not all) document types (js, css, html, etc.) to disappear. When I put preap on the `ignored_packages` list, everything is fine.

**Comment by equinusocio** [comment]
@okonomiyaki3000 i've tested with many themes, and this issue occurs only with "Aproposo" theme, I think is related to "Aprosopo" itself.
