### ISSUE TITLE
Auto complete's background color with the theme's default color scheme

### ISSUE THREAD

**Issue by delroh** [equinusocio/preap#11]
![autocomplete-bg](https://cloud.githubusercontent.com/assets/3700414/7126033/07832c18-e204-11e4-9225-b47a9c150545.png)

Here the auto complete pops to complete the "h". As it has the same background color as the theme's color scheme, it gets confusing. Maybe adding a border will do, but could be anything as long as one can tell the difference.

It's a little confusing for me, but might not be for others. Just letting you know.

**Comment by equinusocio** [comment]
@delroh Only the selected item in the autocomplete panel have the same background color. This is a multi result autocomplete example.

![automplete](https://cloud.githubusercontent.com/assets/10454741/7140347/0a0e0558-e2cb-11e4-975a-666e7a3360f2.png)

**Comment by delroh** [comment]
Oh I see. Never mind then, I'm having a laugh at me now (and a little shame) because I didn't try a multiple result auto complete with this theme until now. Thanks for the reply and thank you for sharing this theme + color scheme.

**Comment by equinusocio** [comment]
:) i will change the BG color of selected item in the next update. If you Mike the theme pla share :)

**Comment by equinusocio** [comment]
:) i will change the BG color of selected item in the next update. If you Mike the theme pla share :)
