### ISSUE TITLE
Remove markdown margin

### ISSUE THREAD

**Issue by Frozenfire92** [equinusocio/preap#12]
While I can see the appeal of having markdown files with a margin. I however find this annoying and would prefer the option to keep it aligned like normal files.

**Comment by Frozenfire92** [comment]
I see [this](https://github.com/equinusocio/preap/blob/master/Prefs/Ext/Markdown.sublime-settings) however I'm not sure how to set that in my user settings

**Comment by equinusocio** [comment]
Hi @Frozenfire92, yes, you can set this in your file preference:

Open a MD file, then go in ""**Preferences > Settings - More > Syntax Specific - User**"" and paste this inside:

```{
    "draw_centered": false,
}```

**Comment by Frozenfire92** [comment]
That worked, thank you :) Also excellent them!

**Comment by equinusocio** [comment]
thanks!
