### ISSUE TITLE
Sidebar Indent

### ISSUE THREAD

**Issue by Wicksio** [equinusocio/preap#15]
Is it possible to change the indent on the side bar? Currently if a directory contains other directories and files the files are indent more than the  directories and would prefer them inline. (thats as clear as mud, see below)

Example: 
![screen shot 2015-06-11 at 11 41 47](https://cloud.githubusercontent.com/assets/12065077/8105194/e73b1c46-102e-11e5-9ec6-a06ef659820d.png)

file.txt and file2.txt are within Example but are indented more.

Thanks

**Comment by equinusocio** [comment]
You can change only the sidebar size and padding. Read here:
https://github.com/equinusocio/preap#sidebar-size-options
