### ISSUE TITLE
Latest build breaks tab icons

### ISSUE THREAD

**Issue by atombender** [equinusocio/preap#4]
Did Sublime upgrade, and Package Control automatically updated the theme, too, which ended up like this.

![screenshot 2015-03-11 10 27 47](https://cloud.githubusercontent.com/assets/50314/6598330/59338c82-c7d9-11e4-980f-6d1eeb176c63.png)

Sublime dev build 3075.

**Comment by darkkain** [comment]
build 3065 win 8.1 
same problem
![default](https://cloud.githubusercontent.com/assets/4064924/6603671/a154aa04-c834-11e4-8d4e-e13cdebf5afd.PNG)

**Comment by equinusocio** [comment]
Thanks. Now all works in the new minor release 1.2.0. Check it in 1 hour
