### ISSUE TITLE
Includes languages that conflict with existing ones

### ISSUE THREAD

**Issue by atombender** [equinusocio/preap#5]
You include a bunch of .tmLanguage files that end up conflicting with other packages. For example, you include `Puppet.tmLanguage`, which causes it to be used instead of the [Puppet](https://packagecontrol.io/packages/Puppet) package. Sublime doesn't have a way to prioritize one language file over another, so when opening such files, they end up being opened without any syntax colouring at all. Apparently you include the language file in order to associate icons with the file names. Is there a solution for this?

**Comment by equinusocio** [comment]
Thanks. I will remove the specifics overrides in the next release.
