### ISSUE TITLE
Breaks tab icons when unsave file

### ISSUE THREAD

**Issue by darkkain** [equinusocio/preap#6]
It's ok:
![zz](https://cloud.githubusercontent.com/assets/4064924/6617272/13a0e238-c8c8-11e4-8eab-bb2a5ce0047b.PNG)

but if preference
```
"show_tab_close_buttons": false,
```
thats look like this:
![bug-st3](https://cloud.githubusercontent.com/assets/4064924/6617246/e320cdbc-c8c7-11e4-9a95-f3e137f0dbef.PNG)

**Comment by equinusocio** [comment]
can you post all you preference settings? I have tested with

```
"show_tab_close_buttons": false,
"tabs_small": true,
```
 and i've no problems with tabs.

![tabs](https://cloud.githubusercontent.com/assets/10454741/6618628/75c0d314-c8c4-11e4-84bc-2d8813bb7cfe.png)

**Comment by darkkain** [comment]
```
"highlight_modified_tabs": true,
```

**Comment by equinusocio** [comment]
@darkkain Ok you're right. I will fix it. Its caused by this settings combination:

```
"highlight_modified_tabs": true,
"show_tab_close_buttons": false,
```

**Comment by darkkain** [comment]
Thx a lot @equinusocio :wink:
Can i request a feature?)

**Comment by equinusocio** [comment]
Yes, sure, but no here. Open new issue with the labels "enhancement" and "question" /play sexyback
