### ISSUE TITLE
Flashing unsaved circle

### ISSUE THREAD

**Issue by andyunleashed** [equinusocio/preap#7]
Hi all,

Absolutely love the theme, 99.9% perfect in every way - but is there a way to disable the flashing of the close circular icon? It's a bit distracting, would be cool if can just have it as a fixed colour.

Cheers!

Andy

**Comment by equinusocio** [comment]
HI @andyunleashed,
thanks for the suggestion, i will add the option to disable it in the next minor update. ;)

**Comment by andyunleashed** [comment]
Awesome stuff, thanks!
