### ISSUE TITLE
font size issues

### ISSUE THREAD

**Issue by okonomiyaki3000** [equinusocio/preap#9]
I'm not 100% sure it's a font size issue but it seems to be. When I'm creating or renaming a file or folder, the dialog that appears at the bottom of the window is half hidden. Makes it very difficult to see what I'm typing. 

Also, not sure if it's related, but the font in the console is quite large. 

If it makes any difference, I'm not using the Preap color scheme. Only the theme. It should not make any difference.

**Comment by equinusocio** [comment]
@okonomiyaki3000 I have no control on the fontsize of console, but is smaller than the original "Default" theme. I will investigate on the first issue, thanks.
